name: Deploy docs to Pages
on:
  push:
    branches:
      - master

  workflow_dispatch:

env:
  PYTHON_VERSION: 3.x

permissions:
  contents: write

jobs:
  deploy:
    name: Build and deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python runtime
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Set up build cache
        uses: actions/cache@v3
        id: cache
        with:
          key: ${{ runner.os }}-${{ hashFiles('.cache/**') }}
          path: .cache

      - name: Install Python dependencies
        run: |
          pip install \
            "cairosvg>=2.5" \
            "mkdocs-git-revision-date-localized-plugin>=1.0" \
            "mkdocs-minify-plugin>=0.3" \
            "mkdocs-git-authors-plugin>=0.6" \
            "mkdocs-git-committers-plugin-2<1" \
            "pillow<10"
      - name: Install build
        run: pip install mkdocs-material

      - name: Deploy
        run: |
          mkdocs gh-deploy --force